apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-s7hf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-s7hf@sha256:b3a508c993d64da03f22a85d2dde82ff23aeecc452501a927713eea5b25fc64f
        name: my-nodejs
        resources: {}
status: {}
